/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculadora;

import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;




/**
 *
 * @author carlos
 */
public class calculadora extends javax.swing.JFrame {

    private String cadenaNumeros="";
    private String operacion ="nula";
    private double primerNumero , resultado;
    private boolean activado = true;
    private boolean punto = true;
    
    /**
     * Creates new form calculadora
     */
    public calculadora() {
        initComponents();
        this.setTitle("Calculadora");
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        botonc = new javax.swing.JButton();
        botonraiz = new javax.swing.JButton();
        botondividir = new javax.swing.JButton();
        botonce = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        botonmultiplicacion = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        botonresta = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        botonsuma = new javax.swing.JButton();
        botonmasomenos = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        botonpunto = new javax.swing.JButton();
        botonigual = new javax.swing.JButton();
        etiquetanumero = new javax.swing.JLabel();
        etiquetaMuestra = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(5, 4));

        botonc.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botonc.setText("C");
        botonc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoncActionPerformed(evt);
            }
        });
        jPanel1.add(botonc);

        botonraiz.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botonraiz.setText("√");
        botonraiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonraizActionPerformed(evt);
            }
        });
        jPanel1.add(botonraiz);

        botondividir.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botondividir.setText("/");
        botondividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botondividirActionPerformed(evt);
            }
        });
        jPanel1.add(botondividir);

        botonce.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botonce.setText("CE");
        botonce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonceActionPerformed(evt);
            }
        });
        jPanel1.add(botonce);

        jButton6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton6.setText("7");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton5.setText("8");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);

        jButton11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton11.setText("9");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton11);

        botonmultiplicacion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botonmultiplicacion.setText("X");
        botonmultiplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonmultiplicacionActionPerformed(evt);
            }
        });
        jPanel1.add(botonmultiplicacion);

        jButton8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton8.setText("4");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8);

        jButton9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton9.setText("5");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9);

        jButton20.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton20.setText("6");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton20);

        botonresta.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botonresta.setText("-");
        botonresta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonrestaActionPerformed(evt);
            }
        });
        jPanel1.add(botonresta);

        jButton16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton16.setText("1");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton16);

        jButton10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton10.setText("2");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton10);

        jButton15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton15.setText("3");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton15);

        botonsuma.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botonsuma.setText("+");
        botonsuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonsumaActionPerformed(evt);
            }
        });
        jPanel1.add(botonsuma);

        botonmasomenos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botonmasomenos.setText("+/-");
        botonmasomenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonmasomenosActionPerformed(evt);
            }
        });
        jPanel1.add(botonmasomenos);

        jButton18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton18.setText("0");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton18);

        botonpunto.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botonpunto.setText(".");
        botonpunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonpuntoActionPerformed(evt);
            }
        });
        jPanel1.add(botonpunto);

        botonigual.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botonigual.setText("=");
        botonigual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonigualActionPerformed(evt);
            }
        });
        jPanel1.add(botonigual);

        etiquetanumero.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        etiquetanumero.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        etiquetanumero.setText("0");

        etiquetaMuestra.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        etiquetaMuestra.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(etiquetaMuestra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(etiquetanumero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 14, Short.MAX_VALUE)
                .addComponent(etiquetaMuestra, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(etiquetanumero, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if(etiquetanumero.getText().equals("0")){  //busca que la etiqueta inicialice en cero
        cadenaNumeros = "7";//el numero que se colocara
        }else{
            cadenaNumeros += "7";//el numero que se mostrara en pantalla
        }     
        etiquetanumero.setText(cadenaNumeros);//convierte el numero en texto en la pantalla
        activado = true;//activa para colocar el numero en pantalla
         
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if(etiquetanumero.getText().equals("0")){  //busca que la etiqueta inicialice en cero
        cadenaNumeros = "8";//el numero que se colocara
        }else{
            cadenaNumeros += "8";//el numero que se mostrara en pantalla
        }     
        etiquetanumero.setText(cadenaNumeros);//convierte el numero en texto en la pantalla
        activado = true;//activa para colocar el numero en pantalla
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
              if(etiquetanumero.getText().equals("0")){  //busca que la etiqueta inicialice en cero
            cadenaNumeros = "9";//el numero que se colocara
        }else{
            cadenaNumeros += "9";//el numero que se mostrara en pantalla
        }     
        etiquetanumero.setText(cadenaNumeros);//convierte el numero en texto en la pantalla
        activado = true;//activa para colocar el numero en pantalla
          
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        if(etiquetanumero.getText().equals("0")){  //busca que la etiqueta inicialice en cero
        cadenaNumeros = "4";//el numero que se colocara
        }else{
            cadenaNumeros += "4";//el numero que se mostrara en pantalla
        }     
        etiquetanumero.setText(cadenaNumeros);//convierte el numero en texto en la pantalla
        activado = true;//activa para colocar el numero en pantalla
          
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        if(etiquetanumero.getText().equals("0")){  //busca que la etiqueta inicialice en cero
        cadenaNumeros = "5";//el numero que se colocara
        }else{
            cadenaNumeros += "5";//el numero que se mostrara en pantalla
        }     
        etiquetanumero.setText(cadenaNumeros);//convierte el numero en texto en la pantalla
        activado = true;//activa para colocar el numero en pantalla
          
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        if(etiquetanumero.getText().equals("0")){  //busca que la etiqueta inicialice en cero
       cadenaNumeros = "6";//el numero que se colocara
        }else{
            cadenaNumeros += "6";//el numero que se mostrara en pantalla
        }     
        etiquetanumero.setText(cadenaNumeros);//convierte el numero en texto en la pantalla
        activado = true;//activa para colocar el numero en pantalla
         
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
             if(etiquetanumero.getText().equals("0")){  //busca que la etiqueta inicialice en cero
            cadenaNumeros = "1";//el numero que se colocara
        }else{
            cadenaNumeros += "1";//el numero que se mostrara en pantalla
        }     
        etiquetanumero.setText(cadenaNumeros);//convierte el numero en texto en la pantalla
        activado = true;//activa para colocar el numero en pantalla
      
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        if(etiquetanumero.getText().equals("0")){  //busca que la etiqueta inicialice en cero
        cadenaNumeros = "2";//el numero que se colocara
        }else{
            cadenaNumeros += "2";//el numero que se mostrara en pantalla
        }     
        etiquetanumero.setText(cadenaNumeros);//convierte el numero en texto en la pantalla
        activado = true;//activa para colocar el numero en pantalla
    
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        if(etiquetanumero.getText().equals("0")){  //busca que la etiqueta inicialice en cero
        cadenaNumeros = "3";//el numero que se colocara
        }else{
            cadenaNumeros += "3";//el numero que se mostrara en pantalla
        }     
        etiquetanumero.setText(cadenaNumeros);//convierte el numero en texto en la pantalla
        activado = true;//activa para colocar el numero en pantalla
     
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
         if(etiquetanumero.getText().equals("0")){  //busca que la etiqueta inicialice en cero
            cadenaNumeros = "0";//el numero que se colocara
        }else{
            cadenaNumeros += "0";//el numero que se mostrara en pantalla
        }     
        etiquetanumero.setText(cadenaNumeros);//convierte el numero en texto en la pantalla
        activado = true;//activa para colocar el numero en pantalla
    }//GEN-LAST:event_jButton18ActionPerformed

    private void botonsumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonsumaActionPerformed
          if(activado==true){
            primerNumero=Double.parseDouble(cadenaNumeros);//convierte el texto en numero
            etiquetaMuestra.setText(cadenaNumeros + " + " );//muestra lo que se hace en la pantalla de etiqueta muestra
            cadenaNumeros="";//se espera que registre la cadena para convertirla en texto
            operacion="Sumar";//operacion que se realizara
            
               activado=false;//activa para realizar la operacion
               punto=true;
        }
    }//GEN-LAST:event_botonsumaActionPerformed

    private void botonigualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonigualActionPerformed
        double segundoNumero;
        
        if(operacion.equals("nula")){
            etiquetanumero.setText(cadenaNumeros);
        }
        
        else if(operacion.equals("Sumar")){  //se elige la operacion que se va a realizar
            segundoNumero = Double.parseDouble(cadenaNumeros); //convierte el texton en numero
            resultado=primerNumero+segundoNumero;//realiza la operacion
            etiquetanumero.setText(String.format("%.2f", resultado));//coloca la condicion de como quedara la respesuta en este caso con 2 cifras decimales
            cadenaNumeros=String.valueOf(resultado);//convierte ese resultado otra ves en string para mostrar en la pantalla
            operacion="nula";//realiza la operacion nula para que vulva a estar como antes
            
        }
        
          else if(operacion.equals("restar")){  //se elige la operacion que se va a realizar
            segundoNumero = Double.parseDouble(cadenaNumeros); //convierte el texton en numero
            resultado=primerNumero-segundoNumero;//realiza la operacion
            etiquetanumero.setText(String.format("%.2f", resultado));//coloca la condicion de como quedara la respesuta en este caso con 2 cifras decimales
            cadenaNumeros=String.valueOf(resultado);//convierte ese resultado otra ves en string para mostrar en la pantalla
            operacion="nula";//realiza la operacion nula para que vulva a estar como antes
            
        }
          
         else if(operacion.equals("multiplicar")){  //se elige la operacion que se va a realizar
            segundoNumero = Double.parseDouble(cadenaNumeros); //convierte el texton en numero
            resultado=primerNumero*segundoNumero;//realiza la operacion
            etiquetanumero.setText(String.format("%.2f", resultado));//coloca la condicion de como quedara la respesuta en este caso con 2 cifras decimales
            cadenaNumeros=String.valueOf(resultado);//convierte ese resultado otra ves en string para mostrar en la pantalla
            operacion="nula";//realiza la operacion nula para que vulva a estar como antes
            
        }
           else if (operacion.equals("dividir")) {  //se elige la operacion que se va a realizar
            segundoNumero = Double.parseDouble(cadenaNumeros);//convierte el texton en numero
            if (segundoNumero == 0) {//genera la condicion de que si se divide por cero esto quedara infinito
                // etiquetanumero.setText("NoSeDividePor0"); //comentario que se mostrara en pantalla
                JOptionPane.showMessageDialog(this,"No se puede dividir entre 0");
            } else {
                resultado = primerNumero / segundoNumero; //operacion a realizar
                etiquetanumero.setText(String.format("% .2f", resultado));//coloca la condicion de como quedara la respesuta en este caso con 2 cifras decimales
                cadenaNumeros = String.valueOf(resultado);//convierte ese resultado otra ves en string para mostrar en la pantalla
                operacion = "nula";//realiza la operacion nula para que vulva a estar como antes
            }
        }
        
                       
        etiquetaMuestra.setText("");
        activado = true;
        punto = false;
    }//GEN-LAST:event_botonigualActionPerformed

    private void botonmultiplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonmultiplicacionActionPerformed
         if(activado==true){
            primerNumero=Double.parseDouble(cadenaNumeros);//convierte el texto en numero
            etiquetaMuestra.setText(cadenaNumeros + " x " );//muestra lo que se hace en la pantalla de etiqueta muestra
            cadenaNumeros="";//se espera que registre la cadena para convertirla en texto
            operacion="multiplicar";//operacion que se realizara
            
               activado=false;//activa para realizar la operacion
               punto=true;
        }        
    }//GEN-LAST:event_botonmultiplicacionActionPerformed

    private void botonrestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonrestaActionPerformed
         if(activado==true){
            primerNumero=Double.parseDouble(cadenaNumeros);//convierte el texto en numero
            etiquetaMuestra.setText(cadenaNumeros + " - " );//muestra lo que se hace en la pantalla de etiqueta muestra
            cadenaNumeros="";//se espera que registre la cadena para convertirla en texto
            operacion="resta";//operacion que se realizara
            
               activado=false;//activa para realizar la operacion
               punto=true;
        }
    }//GEN-LAST:event_botonrestaActionPerformed

    private void botondividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botondividirActionPerformed
       if(activado==true){
            primerNumero=Double.parseDouble(cadenaNumeros);//convierte el texto en numero
            etiquetaMuestra.setText(cadenaNumeros + " / " );//muesta lo que se hace en la pantalla de etiqueta muestra
            cadenaNumeros="";//se espera que registre la cadena para convertila en texto
            operacion="dividir";//operacion que se realizara
            
               activado=false;//activa para realizar la operacion
               punto=true;
        }
    }//GEN-LAST:event_botondividirActionPerformed

    private void botonraizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonraizActionPerformed
        primerNumero=Double.parseDouble(cadenaNumeros);//convierte el texto en numero
        etiquetaMuestra.setText("sqrt("+cadenaNumeros +")" );//convierte el numero en texto y lo muestra en la etiqueta muestra
        resultado=Math.sqrt(primerNumero);//calcula la raiz del primer numero
        etiquetanumero.setText(String.format("%.2f", resultado));//colocamos el formato con 2 decimales
        cadenaNumeros = String.valueOf(resultado);//convertimos el valor a cadena
        
        punto=true;
    }//GEN-LAST:event_botonraizActionPerformed

    private void botonpuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonpuntoActionPerformed
          if(punto == true){
            if(cadenaNumeros.equals("")){ //colocamos una condicion que si esta vacia cadena sera igual a 0.
                cadenaNumeros = "0.";//mostramos esa condicion
            }else{//caso contrario
                cadenaNumeros += ".";//se coloca el punto 
            }
            etiquetanumero.setText(cadenaNumeros);//mostrar la operacion
            punto = false;//vuelve a colcoar el punto falso
        }              
    }//GEN-LAST:event_botonpuntoActionPerformed

    private void botonmasomenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonmasomenosActionPerformed
           if(cadenaNumeros.charAt(0) != '-'){ //combierte el numero con un negativo (//20 es diferente de menos entonces coloque que quede negativo)
            cadenaNumeros = "-" + cadenaNumeros;//como lo muestra en pantalla
        }else{
            cadenaNumeros = cadenaNumeros.substring(1,cadenaNumeros.length());//coloca que la cadena de texto quede positiva
        }
        etiquetanumero.setText(cadenaNumeros);//muestra en pantalla la operacion
    }//GEN-LAST:event_botonmasomenosActionPerformed

    private void botoncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoncActionPerformed
        etiquetaMuestra.setText("");//muestra la pantalla vacia
        etiquetanumero.setText("0");//coloca un cero para volver a inicialiazar
        cadenaNumeros="0";//coloca la cadena numeros sin nada
        operacion="nula";//queda sin operacion asignada
        activado=true;//coloca el activado por defecto
        punto=true;//coloca el punto por defecto
        
    }//GEN-LAST:event_botoncActionPerformed

    private void botonceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonceActionPerformed
        int tamaño = cadenaNumeros.length(); 
        if(tamaño > 0){
            if(tamaño == 1){//compara si el tamaño del texto es 1 entonces respuesta es cero
                cadenaNumeros = "0";//lo que mostrara en pantalla
            }else{
                cadenaNumeros = cadenaNumeros.substring(0,cadenaNumeros.length() - 1);//si el caso contrario tiene mas de una cifra entonces se le quitaria la ultima cifra
            }
            etiquetanumero.setText(cadenaNumeros);//lo mostraria en pantalla
        }
    }//GEN-LAST:event_botonceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws ClassNotFoundException, InstantiationException, IllegalAccessException, UnsupportedLookAndFeelException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        UIManager.setLookAndFeel("com.jtattoo.plaf.aluminium.AluminiumLookAndFeel");
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonc;
    private javax.swing.JButton botonce;
    private javax.swing.JButton botondividir;
    private javax.swing.JButton botonigual;
    private javax.swing.JButton botonmasomenos;
    private javax.swing.JButton botonmultiplicacion;
    private javax.swing.JButton botonpunto;
    private javax.swing.JButton botonraiz;
    private javax.swing.JButton botonresta;
    private javax.swing.JButton botonsuma;
    private javax.swing.JLabel etiquetaMuestra;
    private javax.swing.JLabel etiquetanumero;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
